/*
 * Copyright (C) 2008-2011 TrinityCore <http://www.trinitycore.org/>
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation; either version 2 of the License, or (at your
 * option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program. If not, see <http://www.gnu.org/licenses/>.
 */

#include "SpellAuraEffects.h"

#ifndef DEF_ULDUAR_H
#define DEF_ULDUAR_H

enum eTypes
{
    MAX_ENCOUNTER               = 15,

    TYPE_LEVIATHAN              = 0,
    TYPE_IGNIS                  = 1,
    TYPE_RAZORSCALE             = 2,
    TYPE_XT002                  = 3,
    TYPE_ASSEMBLY               = 4,
    TYPE_KOLOGARN               = 5,
    TYPE_AURIAYA                = 6,
    TYPE_MIMIRON                = 7,
    TYPE_HODIR                  = 8,
    TYPE_THORIM                 = 9,
    TYPE_FREYA                  = 10,
    TYPE_VEZAX                  = 11,
    TYPE_YOGGSARON              = 12,
    TYPE_ALGALON                = 13,
    TYPE_COLOSSUS               = 14,

	// Razorscale
	DATA_EXP_COMMANDER,
	// Kologarn
	DATA_RIGHT_ARM,
	DATA_LEFT_ARM,
	// Auriaya
	DATA_SENTRY_1,
    DATA_SENTRY_2,
    DATA_SENTRY_3,
    DATA_SENTRY_4,
    DATA_FERAL_DEFENDER,
	// Assembly of Iron
    DATA_STEELBREAKER,
    DATA_MOLGEIM,
    DATA_BRUNDIR,
	// Mimiron
    DATA_LEVIATHAN_MK_II,
    DATA_VX_001,
    DATA_AERIAL_UNIT,
    DATA_MAGNETIC_CORE,
	// Thorim
    DATA_RUNIC_COLOSSUS,
    DATA_RUNE_GIANT,
	// Freya
	DATA_BRIGHTLEAF,
    DATA_IRONBRANCH,
    DATA_STONEBARK,
	// Yogg-Saron
    DATA_SARA,
    DATA_BRAIN_DOOR_1,
    DATA_BRAIN_DOOR_2,
    DATA_BRAIN_DOOR_3,
};

enum eNpcs
{
    NPC_LEVIATHAN               = 33113,
    NPC_IGNIS                   = 33118,
    NPC_RAZORSCALE              = 33186,
	NPC_EXPEDITION_COMMANDER    = 33210,
	NPC_RAZORSCALE_CONTROLLER   = 33233,
    NPC_XT002                   = 33293,
    NPC_STEELBREAKER            = 32867,
    NPC_MOLGEIM                 = 32927,
    NPC_BRUNDIR                 = 32857,
    NPC_KOLOGARN                = 32930,
  	NPC_KOLOGARN_BRIDGE         = 34297,
    NPC_RIGHT_ARM               = 32934,
    NPC_LEFT_ARM                = 32933,
    NPC_AURIAYA                 = 33515,
    NPC_SANCTUM_SENTRY          = 34014,
    NPC_FERAL_DEFENDER          = 34035,
    NPC_MIMIRON                 = 33350,
	NPC_MKII                    = 33432,
	NPC_VX001                   = 33651,
	NPC_AERIAL                  = 33670,
	MAGNETIC_CORE               = 34068,
    NPC_HODIR                   = 32845,
    NPC_THORIM                  = 32865,
	NPC_RUNIC_COLOSSUS          = 32872,
	NPC_RUNE_GIANT              = 32873,
    NPC_FREYA                   = 32906,
	NPC_BRIGHTLEAF              = 32915,
	NPC_IRONBRANCH              = 32913,
	NPC_STONEBARK               = 32914,
    NPC_VEZAX                   = 33271,
    NPC_YOGGSARON               = 33288,
	NPC_SARA                    = 33134,
	NPC_FREYA_IMAGE             = 33241,
	NPC_THORIM_IMAGE            = 33242,
	NPC_HODIR_IMAGE             = 33213,
	NPC_MIMIRON_IMAGE           = 33244,
    NPC_ALGALON                 = 32871

};

enum eGameObjects
{
    GO_LEVIATHAN_DOOR       = 194905, // leviathan
    GO_LEVIATHAN_GATE       = 194630,
	GO_SHIELD_DOOR          = 194416,
	GO_LIGHTNING_DOOR       = 194905,
	GO_MOLE_MACHINE         = 194316, // razorscale
	GO_IRON_COUNCIL_DOOR    = 194554, // Iron Council
	GO_ARCHIVUM_DOOR        = 194556,
    GO_KOLOGARN_BRIDGE      = 194232, // kologarn
    GO_RUNIC_DOOR           = 194557, // thorim
    GO_STONE_DOOR           = 194558,
    GO_THORIM_LEVER         = 194265,
    GO_MIMIRON_TRAM         = 194675, // mimiron
    GO_MIMIRON_ELEVATOR     = 194749,
	GO_MIMIRON_DOOR_1       = 194776,
	GO_MIMIRON_DOOR_2       = 194774,
	GO_MIMIRON_DOOR_3       = 194775,
    GO_KEEPERS_DOOR         = 194255, // Vezax
    GO_YOGGSARON_DOOR       = 194773, // yogg-saron
    GO_YOGGBRAIN_DOOR_1     = 194635,
    GO_YOGGBRAIN_DOOR_2     = 194636,
    GO_YOGGBRAIN_DOOR_3     = 194637,
	GO_ALGALON_ACCESS       = 194628, // Algalon
    GO_ALGALON_DOOR_1       = 194911,
    GO_ALGALON_DOOR_2       = 194767,
    GO_ALGALON_PLATFORM     = 194715,
    GO_ALGALON_GLOBE        = 194148,
    GO_ALGALON_BRIDGE       = 194253,
    GO_ALGALON_B_VISUAL     = 194716,
    GO_ALGALON_B_DOOR       = 194910,
    GO_GIFT_OF_THE_OBSERVER = 194821,
};

enum Data
{
    DATA_RUNIC_DOOR,
    DATA_STONE_DOOR,
    DATA_CALL_TRAM,
    DATA_MIMIRON_ELEVATOR,
    DATA_HODIR_RARE_CHEST,
	EVENT_LUNBERJACKED,
	FREYA_ADD_COUNT_DEATH,
	EVENT_BRUNDIR_STUNNED,
	DATA_PORTAL_PHASE,
};

enum eTowerEvents
{
    EVENT_TOWER_OF_STORM_DESTROYED     = 21031,
    EVENT_TOWER_OF_FROST_DESTROYED     = 21032,
    EVENT_TOWER_OF_FLAMES_DESTROYED    = 21033,
    EVENT_TOWER_OF_LIFE_DESTROYED      = 21030
};

enum eAchievements
{
	ACHIEVEMENT_CHAMPION_OF_ULDUAR      = 2903,  // All 10
    ACHIEVEMENT_CONQUEROR_OF_ULDUAR     = 2904,  // All 25
    ACHIEVEMENT_UNBROKEN_10             = 10044, // Leviathan
    ACHIEVEMENT_UNBROKEN_25             = 10045,
	ACHIEVEMENT_LUNBERJACKED_10         = 2979,  // freya
    ACHIEVEMENT_LUNBERJACKED_25         = 3118,
};

enum eAchievementCriteria
{
    ACHIEVEMENT_CRITERIA_SHUTOUT_10                      = 10054, // Leviathan
    ACHIEVEMENT_CRITERIA_SHUTOUT_25                      = 10055,
    ACHIEVEMENT_CRITERIA_3_CAR_GARAGE_CHOPPER_10         = 10046,
    ACHIEVEMENT_CRITERIA_3_CAR_GARAGE_SIEGE_10           = 10047,
    ACHIEVEMENT_CRITERIA_3_CAR_GARAGE_DEMOLISHER_10      = 10048,
    ACHIEVEMENT_CRITERIA_3_CAR_GARAGE_CHOPPER_25         = 10049,
    ACHIEVEMENT_CRITERIA_3_CAR_GARAGE_SIEGE_25           = 10050,
    ACHIEVEMENT_CRITERIA_3_CAR_GARAGE_DEMOLISHER_25      = 10051,
    ACHIEVEMENT_CRITERIA_HOT_POCKET_10                   = 10430, // Ignis
    ACHIEVEMENT_CRITERIA_HOT_POCKET_25                   = 10431,
    ACHIEVEMENT_CRITERIA_QUICK_SHAVE_10                  = 10062, // Razorscale
    ACHIEVEMENT_CRITERIA_QUICK_SHAVE_25                  = 10063,
	ACHIEVEMENT_CRITERIA_THE_ASSASSINATION_OF_KING_LLANE_25   = 10321, // Yogg-Saron
    ACHIEVEMENT_CRITERIA_THE_ASSASSINATION_OF_KING_LLANE_10   = 10324,
    ACHIEVEMENT_CRITERIA_FORGING_OF_THE_DEMON_SOUL_25         = 10322,
    ACHIEVEMENT_CRITERIA_FORGING_OF_THE_DEMON_SOUL_10         = 10325,
    ACHIEVEMENT_CRITERIA_THE_TORTURED_CHAMPION_25             = 10323,
    ACHIEVEMENT_CRITERIA_THE_TORTURED_CHAMPION_10             = 10326,

    ACHIEVEMENT_CRITERIA_KILL_WITHOUT_DEATHS_ALGALON_10       = 10568, // Algalon
    ACHIEVEMENT_CRITERIA_KILL_WITHOUT_DEATHS_ALGALON_25       = 10570,

    ACHIEVEMENT_CRITERIA_KILL_WITHOUT_DEATHS_FLAMELEVIATAN_10 = 10042,
    ACHIEVEMENT_CRITERIA_KILL_WITHOUT_DEATHS_IGNIS_10         = 10342,
    ACHIEVEMENT_CRITERIA_KILL_WITHOUT_DEATHS_RAZORSCALE_10    = 10340,
    ACHIEVEMENT_CRITERIA_KILL_WITHOUT_DEATHS_XT002_10         = 10341,
    ACHIEVEMENT_CRITERIA_KILL_WITHOUT_DEATHS_ASSEMBLY_10      = 10598,
    ACHIEVEMENT_CRITERIA_KILL_WITHOUT_DEATHS_KOLOGARN_10      = 10348,
    ACHIEVEMENT_CRITERIA_KILL_WITHOUT_DEATHS_AURIAYA_10       = 10351,
    ACHIEVEMENT_CRITERIA_KILL_WITHOUT_DEATHS_HODIR_10         = 10439,
    ACHIEVEMENT_CRITERIA_KILL_WITHOUT_DEATHS_THORIM_10        = 10403,
    ACHIEVEMENT_CRITERIA_KILL_WITHOUT_DEATHS_FREYA_10         = 10582,
    ACHIEVEMENT_CRITERIA_KILL_WITHOUT_DEATHS_MIMIRON_10       = 10347,
    ACHIEVEMENT_CRITERIA_KILL_WITHOUT_DEATHS_VEZAX_10         = 10349,
    ACHIEVEMENT_CRITERIA_KILL_WITHOUT_DEATHS_YOGGSARON_10     = 10350,

    ACHIEVEMENT_CRITERIA_KILL_WITHOUT_DEATHS_FLAMELEVIATAN_25 = 10352,
    ACHIEVEMENT_CRITERIA_KILL_WITHOUT_DEATHS_IGNIS_25         = 10355,
    ACHIEVEMENT_CRITERIA_KILL_WITHOUT_DEATHS_RAZORSCALE_25    = 10353,
    ACHIEVEMENT_CRITERIA_KILL_WITHOUT_DEATHS_XT002_25         = 10354,
    ACHIEVEMENT_CRITERIA_KILL_WITHOUT_DEATHS_ASSEMBLY_25      = 10599,
    ACHIEVEMENT_CRITERIA_KILL_WITHOUT_DEATHS_KOLOGARN_25      = 10357,
    ACHIEVEMENT_CRITERIA_KILL_WITHOUT_DEATHS_AURIAYA_25       = 10363,
    ACHIEVEMENT_CRITERIA_KILL_WITHOUT_DEATHS_HODIR_25         = 10719,
    ACHIEVEMENT_CRITERIA_KILL_WITHOUT_DEATHS_THORIM_25        = 10404,
    ACHIEVEMENT_CRITERIA_KILL_WITHOUT_DEATHS_FREYA_25         = 10583,
    ACHIEVEMENT_CRITERIA_KILL_WITHOUT_DEATHS_MIMIRON_25       = 10361,
    ACHIEVEMENT_CRITERIA_KILL_WITHOUT_DEATHS_VEZAX_25         = 10362,
    ACHIEVEMENT_CRITERIA_KILL_WITHOUT_DEATHS_YOGGSARON_25     = 10364,
};

enum eWorldstates
{
    WORLDSTATE_ALGALON_TIME = 4131,
    WORLDSTATE_ALGALON_SHOW = 4132
};

#endif

