	  update creature_template set ScriptName = 'boss_drekthar' where entry = 11946 ;
	  update creature_template set ScriptName = 'boss_galvangar' where entry = 11947;
      update creature_template set ScriptName = 'boss_vanndar' where entry = 11948;
	  update creature_template set ScriptName = 'boss_balinda' where entry = 11949;
      update creature_template set ScriptName = 'AV_Marshals' where entry = 14762 ;
      update creature_template set ScriptName = 'AV_Marshals' where entry = 14763 ;
      update creature_template set ScriptName = 'AV_Marshals' where entry = 14764 ;
      update creature_template set ScriptName = 'AV_Marshals' where entry = 14765 ;
      update creature_template set ScriptName = 'AV_Warmasters' where entry = 14772 ;
      update creature_template set ScriptName = 'AV_Warmasters' where entry = 14773 ;
      update creature_template set ScriptName = 'AV_Warmasters' where entry = 14776 ;
      update creature_template set ScriptName = 'AV_Warmasters' where entry = 14777 ;
      update creature_template set ScriptName = 'AV_Warmasters' where entry = 14770 ;
      update creature_template set ScriptName = 'AV_Warmasters' where entry = 14771 ;
      update creature_template set ScriptName = 'AV_Warmasters' where entry = 14774 ;
      update creature_template set ScriptName = 'AV_Warmasters' where entry = 14775 ;
